### ISSUE TITLE
"space-to-tabs" or "spaces-to-tabs"?

### ISSUE THREAD

**Issue by chase-moskal** [apsdehal/spaces-to-tabs#1]
Inconsistent

**Comment by apsdehal** [comment]
I didn't get you.

**Comment by chase-moskal** [comment]
Readme says: "space-to-tabs"

NPM project is called: "spaces-to-tabs"

Readme even has this inconsistency:

```
$ space-to-tabs -h
Usage: spaces-to-tabs [options] <file ...>
```

**Comment by apsdehal** [comment]
Oh!
Sure, will fix soon.

**Comment by joeyfigaro** [comment]
@apsdehal PR up for ya. :) 

#2
